// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	UserName         string `json:"userName"`
	Mobile           string `json:"mobile"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResponse struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type VerificationRequest struct {
	Mobile string `json:"mobile"`
}

type VerificationResponse struct {
}

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId   int64  `json:"userId"`
	UserName string `json:"userName"`
	Token    string `json:"token"`
}

type UserInfoResponse struct {
	UserId   int64  `json:"userId"`
	UserName string `json:"userName"`
	Mobile   string `json:"mobile"`
}
